# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vBWLG3Jth2ZHUehe0IFbpIt2_OJGklog
"""

import numpy as np

hehe = np.arange(5)

print('hehe')